---
- hosts: hosts
  become: yes
  become_user: root
  tasks:
  - name: install openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: download jenkins.repo
    get_url:
      url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
      state: present
      key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: install jenkins
    yum:
      name: jenkins
      state: present

  - name: start jenkins
    systemd:
      name: jenkins
      state: started

  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: true

  - name: Ensure port 8080 added to firewalld
    firewalld:
      port: 8080/tcp
      state: enabled
      permanent: yes
      immediate: yes